name: CI
on:
  push:
    branches:
      - dev
      - main

  pull_request:
    branches:
      - dev
      - main

jobs:
  quality:
    name: Code Quality
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: "1.4.2"

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: check formatting
        run: bunx prettier --check .

      - name: Run Eslint
        run: bun run lint
